### ISSUE TITLE
checkcommitreadiness 一直返回false

### ISSUE THREAD

**Issue by heiheiheibj** [ShanZJ-gvs/FabricGeneralChainCode#1]
你好
approveformyorg 操作已经通过
peer lifecycle chaincode approveformyorg  -o 127.0.0.1:7050  。。。。。。
 [chaincodeCmd] ClientWait -> txid [9b1956346e9562694ca16d93f6769d4674cd2f276f06ecd75a0ac4a5af2b891f] committed with status (VALID) at 0.0.0.0:7051

但是checkcommitreadiness  Org1MSP 和 Org2MSP 一直返回 一进返回是 false

peer lifecycle chaincode checkcommitreadiness --channelID mychannel --name teaArea-java-demo --version 1.0 --sequence 1 --tls --cafile ${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem --output json

{
	"approvals": {
		"Org1MSP": false,
		"Org2MSP": false
	}
}

请问可能是什么问题呢，谢谢。

**Comment by ShanZJ-gvs** [comment]
checkcommitreadiness是检查，

> 你好 approveformyorg 操作已经通过 peer lifecycle chaincode approveformyorg -o 127.0.0.1:7050 。。。。。。 [chaincodeCmd] ClientWait -> txid [9b1956346e9562694ca16d93f6769d4674cd2f276f06ecd75a0ac4a5af2b891f] committed with status (VALID) at 0.0.0.0:7051
> 
> 但是checkcommitreadiness Org1MSP 和 Org2MSP 一直返回 一进返回是 false
> 
> peer lifecycle chaincode checkcommitreadiness --channelID mychannel --name teaArea-java-demo --version 1.0 --sequence 1 --tls --cafile ${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem --output json
> 
> { "approvals": { "Org1MSP": false, "Org2MSP": false } }
> 
> 请问可能是什么问题呢，谢谢。

检查没通过，也就是你链码安装没成功，或者两个节点没有建立通信，没法准确回答，建议你重现搭一遍

**Comment by heiheiheibj** [comment]
谢谢回复，问题搞定了，把系统格了重装一次就好了，具体原因还未知。。。
麻烦再问一下，现在上链加数据查数据都没问题，但是如何得到数据所在区块的信息，还有交易时产生的交易ID呢。谢谢

**Comment by ShanZJ-gvs** [comment]
> 谢谢回复，问题搞定了，把系统格了重装一次就好了，具体原因还未知。。。
> 麻烦再问一下，现在上链加数据查数据都没问题，但是如何得到数据所在区块的信息，还有交易时产生的交易ID呢。谢谢

在TestConnToNetworkByFabricGateway.java  中有实例操作
